fix config

diff --git a/.deliver/config b/.deliver/config
--- a/.deliver/config
+++ b/.deliver/config
@@ -1,20 +1,49 @@
 APP="funk_and_schuster"
 
-BUILD_HOST="206.189.176.130"
+BUILD_HOST="funkandschuster.art"
 BUILD_USER="tom"
-BUILD_AT="/home/tom/app_build"
+BUILD_AT="/home/tom/funk_and_schuster_build"
 
-PRODUCTION_HOSTS="206.189.176.130"
+PRODUCTION_HOSTS="funkandschuster.art"
 PRODUCTION_USER="tom"
-DELIVER_TO="/home/tom/app_release"
-
+DELIVER_TO="/home/tom/funk_and_schuster_release"
 
 pre_erlang_get_and_update_deps() {
-  local _prod_secret_path="/home/tom/app_config/prod.secret.exs"
+  local _prod_secret_path="/home/tom/funk_and_schuster_config/prod.secret.exs"
   if [ "$TARGET_MIX_ENV" = "prod" ]; then
     __sync_remote "
       ln -sfn '$_prod_secret_path' '$BUILD_AT/config/prod.secret.exs'
-    "
+    "  
   fi
 }
+
+pre_erlang_clean_compile() {
+  status "Preparing assets with: brunch build and phoenix.digest"
+  __sync_remote "
+    # runs the commands on the build host
+    [ -f ~/.profile ] && source ~/.profile # load profile (optional)
+
+    # fail if any command fails (recommended)
+    set -e
+
+    # enter the build directory on the build host (required)
+    cd '$BUILD_AT'
+
+    mkdir -p priv/static # required by the phoenix.digest task
+
+    cd assets
+
+    # installing npm dependencies
+    npm install
+
+    # building brunch
+    node node_modules/brunch/bin/brunch build --production
+    # brunch build --production
+
+    cd '$BUILD_AT'
+
+    # run your custom task
+    APP='$APP' MIX_ENV='$TARGET_MIX_ENV' $MIX_CMD phoenix.digest $SILENCE
+  "
+} 
 
